[18:06:01.175] [ERROR] [main] - Error occurred: (org.openqa.selenium.TimeoutException) (ErrorHandler:forEach:1511) 
[18:06:01.177] [ERROR] [main] - Message: Expected condition failed: waiting for io.github.oneframework.actions.drivers.ContextActions$$Lambda$848/0x000000e801452398@77f04d1a (tried for 30 second(s) with 500 milliseconds interval)
Build info: version: '4.19.1', revision: 'abe0ee07dc'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.5', java.version: '17.0.11'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities {appium:app: /Users/appinventiv/Download..., appium:autoAcceptAlerts: true, appium:autoDismissAlerts: false, appium:automationName: XCuiTest, appium:clearSystemFiles: true, appium:connectHardwareKeyboard: true, appium:databaseEnabled: false, appium:deviceName: iPhone 15 Pro, appium:fullReset: false, appium:isHeadless: false, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:maxTypingFrequency: 35, appium:networkConnectionEnabled: false, appium:noReset: false, appium:platformVersion: 17.4, appium:simulatorStartupTimeout: 180000, appium:takesScreenshot: true, appium:udid: 04077649-5DD1-48EA-A3F0-8DE..., appium:useNewWDA: false, appium:usePrebuiltWDA: false, appium:wdaConnectionTimeout: 120000, appium:wdaLaunchTimeout: 120000, appium:wdaLocalPort: 8101, appium:wdaStartupRetries: 2, appium:wdaStartupRetryInterval: 10000, appium:webStorageEnabled: false, platformName: IOS}
Session ID: 6119b3df-a46a-40eb-823d-4d940cd5dfc1 (ErrorHandler:forEach:1511) 
[18:06:01.177] [ERROR] [main] - 	at org.openqa.selenium.support.ui.WebDriverWait: timeoutException Line Number: 84 (ErrorHandler:forEach:1511) 
[18:06:01.177] [ERROR] [main] - 	at org.openqa.selenium.support.ui.FluentWait: until Line Number: 228 (ErrorHandler:forEach:1511) 
[18:06:01.178] [ERROR] [main] - 	at io.github.oneframework.actions.drivers.DriverActions: lambda$waitUntil$6 Line Number: 134 (ErrorHandler:forEach:1511) 
[18:06:01.178] [ERROR] [main] - 	at io.github.oneframework.actions.CommonActions: performDriverAction Line Number: 107 (ErrorHandler:forEach:1511) 
[18:06:01.178] [ERROR] [main] - 	at io.github.oneframework.actions.drivers.DriverActions: waitUntil Line Number: 132 (ErrorHandler:forEach:1511) 
[18:06:01.179] [ERROR] [main] - 	at io.github.oneframework.actions.drivers.ContextActions: switchToWebView Line Number: 96 (ErrorHandler:forEach:1511) 
[18:06:01.179] [ERROR] [main] - 	at io.github.oneframework.testng.ui.wdio.WdioDemoTest: verifyWebView Line Number: 131 (ErrorHandler:forEach:1511) 
[18:06:01.179] [ERROR] [main] - 	at io.github.oneframework.testng.ui.wdio.WdioDemoTest: testWebView Line Number: 126 (ErrorHandler:forEach:1511) 
[18:06:01.179] [ERROR] [main] - 	at jdk.internal.reflect.NativeMethodAccessorImpl: invoke0 Line Number: -2 (ErrorHandler:forEach:1511) 
[18:06:01.180] [ERROR] [main] - 	at jdk.internal.reflect.NativeMethodAccessorImpl: invoke Line Number: 77 (ErrorHandler:forEach:1511) 
[18:06:01.180] [ERROR] [main] - 	at jdk.internal.reflect.DelegatingMethodAccessorImpl: invoke Line Number: 43 (ErrorHandler:forEach:1511) 
[18:06:01.180] [ERROR] [main] - 	at java.lang.reflect.Method: invoke Line Number: 568 (ErrorHandler:forEach:1511) 
[18:06:01.181] [ERROR] [main] - 	at org.testng.internal.invokers.MethodInvocationHelper: invokeMethod Line Number: 141 (ErrorHandler:forEach:1511) 
[18:06:01.181] [ERROR] [main] - 	at org.testng.internal.invokers.TestInvoker: invokeMethod Line Number: 686 (ErrorHandler:forEach:1511) 
[18:06:01.181] [ERROR] [main] - 	at org.testng.internal.invokers.TestInvoker: invokeTestMethod Line Number: 230 (ErrorHandler:forEach:1511) 
[18:06:01.182] [ERROR] [main] - 	at org.testng.internal.invokers.MethodRunner: runInSequence Line Number: 63 (ErrorHandler:forEach:1511) 
[18:06:01.182] [ERROR] [main] - 	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent: invoke Line Number: 992 (ErrorHandler:forEach:1511) 
[18:06:01.182] [ERROR] [main] - 	at org.testng.internal.invokers.TestInvoker: invokeTestMethods Line Number: 203 (ErrorHandler:forEach:1511) 
[18:06:01.182] [ERROR] [main] - 	at org.testng.internal.invokers.TestMethodWorker: invokeTestMethods Line Number: 154 (ErrorHandler:forEach:1511) 
[18:06:01.183] [ERROR] [main] - 	at org.testng.internal.invokers.TestMethodWorker: run Line Number: 134 (ErrorHandler:forEach:1511) 
[18:06:01.183] [ERROR] [main] - 	at java.util.ArrayList: forEach Line Number: 1,511 (ErrorHandler:forEach:1511) 
[18:06:01.183] [ERROR] [main] - 	at org.testng.TestRunner: privateRun Line Number: 739 (ErrorHandler:forEach:1511) 
[18:06:01.183] [ERROR] [main] - 	at org.testng.TestRunner: run Line Number: 614 (ErrorHandler:forEach:1511) 
[18:06:01.184] [ERROR] [main] - 	at org.testng.SuiteRunner: runTest Line Number: 421 (ErrorHandler:forEach:1511) 
[18:06:01.184] [ERROR] [main] - 	at org.testng.SuiteRunner: runSequentially Line Number: 413 (ErrorHandler:forEach:1511) 
[18:06:01.184] [ERROR] [main] - 	at org.testng.SuiteRunner: privateRun Line Number: 373 (ErrorHandler:forEach:1511) 
[18:06:01.184] [ERROR] [main] - 	at org.testng.SuiteRunner: run Line Number: 312 (ErrorHandler:forEach:1511) 
[18:06:01.184] [ERROR] [main] - 	at org.testng.SuiteRunnerWorker: runSuite Line Number: 52 (ErrorHandler:forEach:1511) 
[18:06:01.185] [ERROR] [main] - 	at org.testng.SuiteRunnerWorker: run Line Number: 95 (ErrorHandler:forEach:1511) 
[18:06:01.185] [ERROR] [main] - 	at org.testng.TestNG: runSuitesSequentially Line Number: 1,274 (ErrorHandler:forEach:1511) 
[18:06:01.185] [ERROR] [main] - 	at org.testng.TestNG: runSuitesLocally Line Number: 1,208 (ErrorHandler:forEach:1511) 
[18:06:01.185] [ERROR] [main] - 	at org.testng.TestNG: runSuites Line Number: 1,112 (ErrorHandler:forEach:1511) 
[18:06:01.186] [ERROR] [main] - 	at org.testng.TestNG: run Line Number: 1,079 (ErrorHandler:forEach:1511) 
[18:06:01.186] [ERROR] [main] - 	at com.intellij.rt.testng.IDEARemoteTestNG: run Line Number: 65 (ErrorHandler:forEach:1511) 
[18:06:01.186] [ERROR] [main] - 	at com.intellij.rt.testng.RemoteTestNGStarter: main Line Number: 105 (ErrorHandler:forEach:1511) 
[18:06:01.382] [ERROR] [main] - Catching (DriverActions:lambda$saveLogs$5:120) An unknown server-side error occurred while processing the command. Original error: No logs of type 'performance' found.
Build info: version: '4.19.1', revision: 'abe0ee07dc'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.5', java.version: '17.0.11'
Driver info: io.appium.java_client.ios.IOSDriver
Command: [6119b3df-a46a-40eb-823d-4d940cd5dfc1, getLog {type=performance}]
Capabilities {appium:app: /Users/appinventiv/Download..., appium:autoAcceptAlerts: true, appium:autoDismissAlerts: false, appium:automationName: XCuiTest, appium:clearSystemFiles: true, appium:connectHardwareKeyboard: true, appium:databaseEnabled: false, appium:deviceName: iPhone 15 Pro, appium:fullReset: false, appium:isHeadless: false, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:maxTypingFrequency: 35, appium:networkConnectionEnabled: false, appium:noReset: false, appium:platformVersion: 17.4, appium:simulatorStartupTimeout: 180000, appium:takesScreenshot: true, appium:udid: 04077649-5DD1-48EA-A3F0-8DE..., appium:useNewWDA: false, appium:usePrebuiltWDA: false, appium:wdaConnectionTimeout: 120000, appium:wdaLaunchTimeout: 120000, appium:wdaLocalPort: 8101, appium:wdaStartupRetries: 2, appium:wdaStartupRetryInterval: 10000, appium:webStorageEnabled: false, platformName: IOS}
Session ID: 6119b3df-a46a-40eb-823d-4d940cd5dfc1
